[metadata]
name = pipnick
description = Photometric Pipeline for the Nickel Telescope
long_description = file: README.md
long_description_content_type = text/markdown
author = Allison K. Eto
author_email = allisonketo@gmail.com
license = BSD-3
url = https://github.com/allisoneto/pipnick
edit_on_github = False
github_project = allisoneto/pipnick
keywords = photometry, astrometry, astronomy, Nickel, UCO, instrumentation, 
classifiers =
    Development Status :: 4 - Beta
    Intended Audience :: Science/Research
    License :: OSI Approved :: BSD License
    Natural Language :: English
    Operating System :: OS Independent
    Programming Language :: Python
    Programming Language :: Python :: 3.11
    Programming Language :: Python :: 3.12
    Programming Language :: Python :: 3.13
    Topic :: Scientific/Engineering :: Astronomy
    Topic :: Software Development :: Libraries :: Python Modules
    Topic :: Software Development :: User Interfaces

[options]
zip_safe = False
use_2to3 = False
packages = find:
python_requires = >=3.11
setup_requires = setuptools_scm
include_package_data = True
install_requires =
    numpy>=2.0
    astropy>=7.0
    photutils>=1.12
    ccdproc>=2.4
    astroquery>=0.4
    extension-helpers>=0.1
    requests>=2.32
    scipy>=1.13
    matplotlib>=3.9
    scikit-image>=0.24
    setuptools_scm>=8.1
    pandas>=2.2
    loess>=2.1

# leave alone
[options.extras_require]
test =
    pytest>=6.2
    pytest-astropy
    tox
    pytest-cov
    coverage
    codecov
docs =
    sphinx
    sphinx-automodapi
    sphinx_rtd_theme
dev =
    pytest>=6.2
    pytest-astropy
    tox
    pytest-cov
    coverage
    codecov
    sphinx
    sphinx-automodapi
    sphinx_rtd_theme

[options.package_data]
* = *.md, data/*, data/*/*

# These are all the scripts
[options.entry_points]
console_scripts = 
      pipnick_reduction = pipnick.scripts.reduction_script:ReductionPipeline.entry_point
      pipnick_astrometry = pipnick.scripts.astrometry_script:AstrometryPipeline.entry_point
      pipnick_photometry = pipnick.scripts.photometry_script:PhotometryPipeline.entry_point

[coverage:run]
omit =
    # fiberlab/tests/*
    pipnick/version*

[coverage:report]
exclude_lines =
    # Have to re-enable the standard pragma
    pragma: no cover
    # Don't complain about packages we have installed
    except ImportError
    # Don't complain if tests don't hit assertions
    raise AssertionError
    raise NotImplementedError
    # Don't complain about script hooks
    def main\(.*\):
    # Ignore branches that don't pertain to this version of Python
    pragma: py{ignore_python_version}
    # Don't complain about IPython completion helper
    def _ipython_key_completions_


